import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs' 
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import design from '../public/design.png'
import code from '../public/code.png'
import Image from 'next/image' 
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Claudia Gillota Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        {/* first page */}
        <section className="min-h-screen"> 
       <nav className="py-10 mb-12 flex justify-between dark:text-white">
        <h1 className="text-xl font-burtons">Developed by Claudia</h1>
          <ul className="flex iteams-center">
            <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} 
            className=" cursor-pointer text-2xl"/> 
            </li>
            <li>
              <a className="bg-gradiant-to-b bg-cyan-500 to-teal-500 text-white px-4 py-2 rouned-md ml-8" href="#">Resume</a>
              </li>
          </ul>
        </nav> 
        <div className="text-center p-10">
          <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">Claudia Gillota</h2>
          <h3 className="text-2xl py-2 dark:text-white md:text-3xl">Developer</h3>
          <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-xl mx-auto">CodeCrafted Journeys: Crafting Innovation One Line at a Time</p>
        </div> 
        <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
<AiFillLinkedin/> 
<AiFillGithub/>
        </div> 
        <div className="">
Hey you left off here at minute 26:00 its a image of yourself you dont have. option to add it later (he also adds a md:h-96 md:w-96 later in the video for medium screens):)
        </div>        
        </section> 
        {/* second page */} 
        <section>
        <div>
          <h3 className="text-3xl py-1 dark:text-white">My Skills </h3> 
          <p className=" text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Since completing the edX fullstack web development bootcamp, I have been working on a variety of projects to build my skills. I have experience with<span className="text-teal-500"> HTML, CSS, JavaScript, React, Next.js, Node.js, Express, MongoDB, and MySQL. </span> I am also familiar with <span className="text-teal-500"> GraphQL and the MERN Stack.</span> I am currently working on a project using React, GraphQL, Node.js, express, MongoDB along with Mongo ODM. I am always looking for new opportunities to learn and grow as a developer.
          </p>
        </div>
        <div className="lg:flex gap-10">
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <Image src={design} alt="design"  width={100} height={100} />  
            <h3 className="tex-lg font-medium pt-8 pb-2">Beautiful Designs</h3>  
            <p className="py-2">Creating elegant designs suited for all needs following code design theory</p>
            <h4 className="py-4 text-teal-500">Design Tools I have used</h4> 
            <ul>
              <li className="text-gray-800 py-1">Bootstrap</li>
              <li className="text-gray-800 py-1">Tailwind</li>
              <li className="text-gray-800 py-1">Material UI</li>
              <li className="text-gray-800 py-1">Bulma</li>
              </ul>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <Image src={code} alt="code"  width={100} height={100} />  
            <h3 className="tex-lg font-medium pt-8 pb-2">Fullstack Coding</h3>  
            <p className="py-2">Creating Full Stack Web Applictions</p>
            <h4 className="py-4 text-teal-500">Coding Tools I have used</h4> 
            <ul>
              <li className="text-gray-800 py-1"> React</li>
              <li className="text-gray-800 py-1">Node.js</li>
              <li className="text-gray-800 py-1">MongoDB</li>
              <li className="text-gray-800 py-1">GraphQL</li>
              </ul>
          </div>
        </div> 
        </section>
        {/* third page */}
        <section> 
          <div>
           <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
           <p className=" text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
          Here are some of the applications I have made so far. They are amazing examples of my knowledge and ability to implement all of the <span className="text-teal-500"> skills  </span> I have learned so far. I am always working on new projects and will be adding them here as I complete them. 
          </p> 
          </div> 
          {/* <div>this were we add our images of our work wrap each one in its own div :) he adds flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap later on in video... to each image div he adds basis-1/3 flex-1... to the image he adds rounded-lg object-cover width={'100%'} height={'100%'} layout="responsive" </div> */}
          </section>
      </main>
    </div>
  );
};
