import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs' 
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Claudia Gillota Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen"> 
       <nav className="py-10 mb-12 flex justify-between">
        <h1 className="text-xl font-burtons">Developed by Claudia</h1>
          <ul className="flex iteams-center">
            <li><BsFillMoonStarsFill className="cursor-pointer-xl"/> 
            </li>
            <li>
              <a className="bg-gradiant-to-r bg-cyan-500 to-teal-500 text-white px-4 py-2 rouned-md ml-8" href="#">Resume</a>
              </li>
          </ul>
        </nav> 
        <div className="text-center p-10">
          <h2 className="text-5xl py-2 text-teal-600">Claudia Gillota</h2>
          <h3 className="text-2xl py-2">Developer</h3>
          <p className="text-md py-5 leading-8 text-gray-800 ">CodeCrafted Journeys: Crafting Innovation One Line at a Time</p>
        </div> 
        <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
<AiFillLinkedin/> 
<AiFillGithub/>
        </div> 
        <div className="">
Hey you left off here at minute 26:00 its a image of yourself you dont have. option to add it later :)
        </div>


        
        </section>
 
      </main>

   
    </div>
  )
}
